# Neden NumPy?

In [392]:
a = [1,2,3,4]
b = [2,3,4,5]

In [393]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [394]:
import numpy as np

In [395]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [396]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [397]:
import numpy as np

In [398]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [399]:
a = np.array([1,2,3,4,5])

In [400]:
type(a)

numpy.ndarray

In [401]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [402]:
#sifirdan array olusturma 

In [403]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [404]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [405]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [406]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [407]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [408]:
np.random.normal(10, 4, (3,4))

array([[12.24816752,  7.69014215,  9.2878282 , 17.22863628],
       [ 6.24548772, 11.77593277,  9.47051465, 14.39780269],
       [15.31472224,  5.59090417, 12.68530435, 11.77073442]])

In [409]:
np.random.randint(0,10, (3,3))

array([[6, 6, 4],
       [3, 9, 6],
       [5, 4, 5]])

# Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [410]:
import numpy as np

In [411]:
np.random.randint(10, size = 10)

array([5, 9, 8, 5, 6, 9, 9, 2, 5, 5])

In [412]:
a = np.random.randint(10, size = 10)

In [413]:
a.ndim

1

In [414]:
a.shape

(10,)

In [415]:
a.size

10

In [416]:
a.dtype

dtype('int32')

In [417]:
b = np.random.randint(10, size = (3,5))

In [418]:
b

array([[8, 4, 9, 8, 0],
       [7, 3, 2, 9, 0],
       [5, 9, 5, 4, 0]])

In [419]:
b.ndim

2

In [420]:
b.shape

(3, 5)

In [421]:
b.size

15

In [422]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [423]:
import numpy as np

In [424]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [425]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [426]:
a = np.arange(1,10)

In [427]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [428]:
a.ndim

1

In [429]:
b = a.reshape((1,9))

In [430]:
b.ndim

2

# Array Birlestirme (Concatenation)

In [431]:
import numpy as np

In [432]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [433]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [434]:
z = np.array([7,8,9])

In [435]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [436]:
#iki boyut

In [437]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [438]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [439]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [440]:
import numpy as np

In [441]:
x = np.array([1,2,3,99,99,3,2,1])

In [442]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [443]:
a,b,c = np.split(x, [3,5])

In [444]:
a

array([1, 2, 3])

In [445]:
b

array([99, 99])

In [446]:
c

array([3, 2, 1])

In [447]:
#iki boyutlu ayırma

In [448]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [449]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [450]:
ust, alt = np.vsplit(m, [2])

In [451]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [452]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [453]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [454]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [455]:
sag, sol = np.hsplit(m, [2])

In [456]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [457]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [458]:
import numpy as np

In [459]:
v = np.array([2,1,4,3,5])

In [460]:
v

array([2, 1, 4, 3, 5])

In [461]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [462]:
v

array([2, 1, 4, 3, 5])

In [463]:
v.sort()

In [464]:
v

array([1, 2, 3, 4, 5])

In [465]:
#iki boyutlu array siralama

In [466]:
m = np.random.normal(20,5, (3,3))

In [467]:
m

array([[21.02354116, 16.55293507, 18.55096651],
       [23.25943667, 23.30312836, 17.11997658],
       [19.63286473, 20.55386579, 24.41963124]])

In [468]:
np.sort(m, axis = 1)

array([[16.55293507, 18.55096651, 21.02354116],
       [17.11997658, 23.25943667, 23.30312836],
       [19.63286473, 20.55386579, 24.41963124]])

In [469]:
np.sort(m, axis = 0)

array([[19.63286473, 16.55293507, 17.11997658],
       [21.02354116, 20.55386579, 18.55096651],
       [23.25943667, 23.30312836, 24.41963124]])

# Index ile Elemanlara Erişmek

In [470]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([8, 6, 5, 3, 6, 6, 2, 2, 5, 9])

In [471]:
a[0]

8

In [472]:
a[-1]

9

In [473]:
a[0] = 100

In [474]:
a

array([100,   6,   5,   3,   6,   6,   2,   2,   5,   9])

In [475]:
m = np.random.randint(10, size = (3,5))
m

array([[6, 6, 4, 2, 4],
       [5, 8, 1, 9, 8],
       [4, 3, 7, 2, 6]])

In [476]:
m[0,0]

6

In [477]:
m[1,1]

8

In [478]:
m[1, 4]

8

In [479]:
m[1, 4] = 99

In [480]:
m

array([[ 6,  6,  4,  2,  4],
       [ 5,  8,  1,  9, 99],
       [ 4,  3,  7,  2,  6]])

In [481]:
m[1,4] = 2.2

In [482]:
m

array([[6, 6, 4, 2, 4],
       [5, 8, 1, 9, 2],
       [4, 3, 7, 2, 6]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [483]:
import numpy as np

In [484]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [485]:
a[0:3]

array([20, 21, 22])

In [486]:
a[:3]

array([20, 21, 22])

In [487]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [488]:
a[1::2]

array([21, 23, 25, 27, 29])

In [489]:
a[0::2]

array([20, 22, 24, 26, 28])

In [490]:
a[2::2]

array([22, 24, 26, 28])

In [491]:
a[0::3]

array([20, 23, 26, 29])

In [492]:
#iki boyutlu slice islemleri

In [493]:
m = np.random.randint(10, size = (5,5))

In [494]:
m

array([[0, 9, 5, 1, 3],
       [0, 8, 7, 2, 8],
       [2, 8, 6, 7, 0],
       [7, 8, 9, 4, 3],
       [0, 1, 7, 0, 6]])

In [495]:
m[:,0]

array([0, 0, 2, 7, 0])

In [496]:
m[:,1]

array([9, 8, 8, 8, 1])

In [497]:
m[:,4]

array([3, 8, 0, 3, 6])

In [498]:
m

array([[0, 9, 5, 1, 3],
       [0, 8, 7, 2, 8],
       [2, 8, 6, 7, 0],
       [7, 8, 9, 4, 3],
       [0, 1, 7, 0, 6]])

In [499]:
m[0,:]

array([0, 9, 5, 1, 3])

In [500]:
m[0]

array([0, 9, 5, 1, 3])

In [501]:
m[1,:]

array([0, 8, 7, 2, 8])

In [502]:
m[0:2, 0:3]

array([[0, 9, 5],
       [0, 8, 7]])

In [503]:
m[:,0:2]

array([[0, 9],
       [0, 8],
       [2, 8],
       [7, 8],
       [0, 1]])

In [504]:
m

array([[0, 9, 5, 1, 3],
       [0, 8, 7, 2, 8],
       [2, 8, 6, 7, 0],
       [7, 8, 9, 4, 3],
       [0, 1, 7, 0, 6]])

In [505]:
m[1:3, 0:2]

array([[0, 8],
       [2, 8]])

# Alt Küme Üzerinde İşlem Yapmak

In [506]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[1, 3, 4, 5, 6],
       [5, 0, 5, 1, 2],
       [6, 9, 9, 5, 9],
       [3, 7, 1, 2, 1],
       [4, 1, 3, 3, 3]])

In [507]:
alt_a = a[0:3, 0:2]
alt_a

array([[1, 3],
       [5, 0],
       [6, 9]])

In [508]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [509]:
alt_a

array([[99999,     3],
       [    5,   888],
       [    6,     9]])

In [510]:
a

array([[99999,     3,     4,     5,     6],
       [    5,   888,     5,     1,     2],
       [    6,     9,     9,     5,     9],
       [    3,     7,     1,     2,     1],
       [    4,     1,     3,     3,     3]])

In [511]:
m = np.random.randint(10, size = (5, 5))
m

array([[2, 2, 0, 9, 7],
       [2, 6, 3, 8, 5],
       [0, 9, 5, 2, 0],
       [9, 7, 6, 3, 3],
       [9, 5, 3, 4, 9]])

In [512]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[2, 2],
       [2, 6],
       [0, 9]])

In [513]:
alt_b[0,0] = 9999

In [514]:
alt_b

array([[9999,    2],
       [   2,    6],
       [   0,    9]])

In [515]:
m

array([[2, 2, 0, 9, 7],
       [2, 6, 3, 8, 5],
       [0, 9, 5, 2, 0],
       [9, 7, 6, 3, 3],
       [9, 5, 3, 4, 9]])

# Fancy Index ile Elemanlara Erişmek

In [516]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [517]:
v[1]

3

In [518]:
v[3]

9

In [519]:
v[5]

15

In [520]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [521]:
al_getir = [1,3,5]

In [522]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [523]:
v[al_getir]

array([ 3,  9, 15])

In [524]:
#iki boyutta fancy

In [525]:
m = np.arange(9).reshape((3,3))

In [526]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [527]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [528]:
m[satir, sutun]

array([1, 5])

In [529]:
#basit index ile fancy index

In [530]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [531]:
m[0, [1,2]]

array([1, 2])

In [532]:
#slice ile fancy

In [533]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [534]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [535]:
v < 3

array([ True,  True, False, False, False])

In [536]:
v[v < 3]

array([1, 2])

In [537]:
v[v > 3]

array([4, 5])

In [538]:
v[v >= 3]

array([3, 4, 5])

In [539]:
v[v <= 3]

array([1, 2, 3])

In [540]:
v[v == 3]

array([3])

In [541]:
v[v != 3]

array([1, 2, 4, 5])

In [542]:
v

array([1, 2, 3, 4, 5])

In [543]:
v * 2

array([ 2,  4,  6,  8, 10])

In [544]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [545]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [546]:
v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

In [547]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [548]:
v - 1

array([0, 1, 2, 3, 4])

In [549]:
v * 5

array([ 5, 10, 15, 20, 25])

In [550]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [551]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [552]:
#ufunc

In [553]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [554]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [555]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [556]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [557]:
v**2

array([ 1,  4,  9, 16, 25])

In [558]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [559]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [560]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [561]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [562]:
np.absolute(np.array([-3]))

array([3])

In [563]:
np.sin(360)

0.9589157234143065

In [564]:
np.cos(180)

-0.5984600690578581

In [565]:
v = np.array([1,2,3])

In [566]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [567]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [568]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [569]:
#cheatsheet

# İstatistiksel Hesaplamalar

In [570]:
v

array([1, 2, 3])

In [571]:
np.mean(v)

2.0

In [572]:
v.sum()

6

In [573]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [574]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [575]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [576]:
a

array([[5, 1],
       [1, 3]])

In [577]:
b

array([12, 10])

In [578]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

# BOLUM SONU DEGERLENDIRMESI

# Pandas Serisi Oluşturmak

In [579]:
import pandas as pd 

In [580]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [581]:
seri = pd.Series([10,88,3,4,5])

In [582]:
type(seri)

pandas.core.series.Series

In [583]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [584]:
seri.dtype

dtype('int64')

In [585]:
seri.size

5

In [586]:
seri.ndim

1

In [587]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [588]:
seri.head(3)

0    10
1    88
2     3
dtype: int64

In [589]:
seri.tail(3)

2    3
3    4
4    5
dtype: int64

In [590]:
#index isimlendirmesi

In [591]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [592]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [593]:
pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [594]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [595]:
seri["a"]

99

In [596]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [597]:
#sozluk uzerinden liste olusturmak

In [598]:
sozluk = {"reg":10, "log":11, "cart": 12}

In [599]:
seri = pd.Series(sozluk)

In [600]:
seri

reg     10
log     11
cart    12
dtype: int64

In [601]:
#iki seriyi birlestirerek seri olusturma

In [602]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman İşlemleri

In [603]:
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [604]:
seri[0]

1

In [605]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [606]:
seri = pd.Series([121,200,150,99], 
                 index = ["reg","loj","cart","rf"])

In [607]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [608]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [609]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [610]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [611]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [612]:
#eleman sorgulama

In [613]:
"reg" in seri

True

In [614]:
"a" in seri

False

In [615]:
seri["reg"]

121

In [616]:
#fancy eleman

In [617]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [618]:
seri["reg"] = 130

In [619]:
seri["reg"]

130

In [620]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

# Pandas DataFrame Oluşturma

In [621]:
import pandas as pd

In [622]:
l = [1,2,39,67,90]

In [623]:
l

[1, 2, 39, 67, 90]

In [624]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [625]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [626]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [627]:
#df isimlendirme

In [628]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [629]:
df.columns = ("deg1","deg2","deg3")

In [630]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [631]:
type(df)

pandas.core.frame.DataFrame

In [632]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [633]:
df.shape

(3, 3)

In [634]:
df.ndim

2

In [635]:
df.size

9

In [636]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [637]:
type(df.values)

numpy.ndarray

In [638]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [639]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [640]:
a = np.array([1,2,3,4,5])

In [641]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Eleman İşlemleri

In [642]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [643]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [644]:
sozluk

{'var1': array([3, 6, 7, 3, 1]),
 'var2': array([4, 0, 8, 6, 0]),
 'var3': array([7, 1, 5, 7, 1])}

In [645]:
df = pd.DataFrame(sozluk)

In [646]:
df

var1  var2  var3
0     3     4     7
1     6     0     1
2     7     8     5
3     3     6     7
4     1     0     1

In [647]:
df[0:1]

var1  var2  var3
0     3     4     7

In [648]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [649]:
df.index = ["a","b","c","d","e"]

In [650]:
df

var1  var2  var3
a     3     4     7
b     6     0     1
c     7     8     5
d     3     6     7
e     1     0     1

In [651]:
df["c":"e"]

var1  var2  var3
c     7     8     5
d     3     6     7
e     1     0     1

In [652]:
#silme

In [653]:
df.drop("a", axis = 0)

var1  var2  var3
b     6     0     1
c     7     8     5
d     3     6     7
e     1     0     1

In [654]:
df

var1  var2  var3
a     3     4     7
b     6     0     1
c     7     8     5
d     3     6     7
e     1     0     1

In [655]:
df.drop("a", axis = 0, inplace = True)

In [656]:
df

var1  var2  var3
b     6     0     1
c     7     8     5
d     3     6     7
e     1     0     1

In [657]:
#fancy 

In [658]:
l = ["c","e"]

In [659]:
df.drop(l, axis = 0)

var1  var2  var3
b     6     0     1
d     3     6     7

In [660]:
#degiskenler icin

In [661]:
df

var1  var2  var3
b     6     0     1
c     7     8     5
d     3     6     7
e     1     0     1

In [662]:
"var1" in df

True

In [663]:
l = ["var1","var4","var2"]

In [664]:
for i in l:
    print(i in df)

True
False
True


In [665]:
df

var1  var2  var3
b     6     0     1
c     7     8     5
d     3     6     7
e     1     0     1

In [666]:
df["var1"]

b    6
c    7
d    3
e    1
Name: var1, dtype: int32

In [667]:
df["var4"] = df["var1"] / df["var2"]

In [668]:
df

var1  var2  var3   var4
b     6     0     1    inf
c     7     8     5  0.875
d     3     6     7  0.500
e     1     0     1    inf

In [669]:
#degisken silmek

In [670]:
df.drop("var4", axis = 1)

var1  var2  var3
b     6     0     1
c     7     8     5
d     3     6     7
e     1     0     1

In [671]:
df

var1  var2  var3   var4
b     6     0     1    inf
c     7     8     5  0.875
d     3     6     7  0.500
e     1     0     1    inf

In [672]:
df.drop("var4", axis = 1, inplace = True)

In [673]:
df

var1  var2  var3
b     6     0     1
c     7     8     5
d     3     6     7
e     1     0     1

In [674]:
l = ["var1","var2"]

In [675]:
df.drop(l, axis = 1)

var3
b     1
c     5
d     7
e     1

# Gözlem ve Değişken Seçimi: loc & iloc

In [676]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    10    12     9
1    26     5    19
2    28    23    13
3    29    29    18
4    20    10    28
5     1    21     9
6    17    22    16
7    18    25    27
8    16    21     4
9     7    19    28

In [677]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [678]:
df.loc[0:3]

var1  var2  var3
0    10    12     9
1    26     5    19
2    28    23    13
3    29    29    18

In [679]:
#iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [680]:
df.iloc[0:3]

var1  var2  var3
0    10    12     9
1    26     5    19
2    28    23    13

In [681]:
df.iloc[0,0]

10

In [682]:
df

var1  var2  var3
0    10    12     9
1    26     5    19
2    28    23    13
3    29    29    18
4    20    10    28
5     1    21     9
6    17    22    16
7    18    25    27
8    16    21     4
9     7    19    28

In [683]:
df.iloc[:3,:2]

var1  var2
0    10    12
1    26     5
2    28    23

In [684]:
df.loc[0:3, "var3"]

0     9
1    19
2    13
3    18
Name: var3, dtype: int32

In [685]:
df.loc[0:3, "var3"]

0     9
1    19
2    13
3    18
Name: var3, dtype: int32

In [686]:
df.iloc[0:3]["var3"]

0     9
1    19
2    13
Name: var3, dtype: int32

# Koşullu Eleman İşlemleri

In [687]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    20     7     8
1     9    15    15
2    16     8     7
3    18    23     3
4    15    21    28
5    28    20    22
6    16    21    15
7    23     8    18
8    28    25    25
9    14    29     6

In [688]:
df["var1"]

0    20
1     9
2    16
3    18
4    15
5    28
6    16
7    23
8    28
9    14
Name: var1, dtype: int32

In [689]:
df[0:2][["var1","var2"]]

var1  var2
0    20     7
1     9    15

In [690]:
df

var1  var2  var3
0    20     7     8
1     9    15    15
2    16     8     7
3    18    23     3
4    15    21    28
5    28    20    22
6    16    21    15
7    23     8    18
8    28    25    25
9    14    29     6

In [691]:
df.var1

0    20
1     9
2    16
3    18
4    15
5    28
6    16
7    23
8    28
9    14
Name: var1, dtype: int32

In [692]:
df[df.var1 > 15]

var1  var2  var3
0    20     7     8
2    16     8     7
3    18    23     3
5    28    20    22
6    16    21    15
7    23     8    18
8    28    25    25

In [693]:
df[(df.var1 > 15) & (df.var3 < 5)]

var1  var2  var3
3    18    23     3

In [694]:
df.loc[(df.var1 > 15), ["var1","var2"]]

var1  var2
0    20     7
2    16     8
3    18    23
5    28    20
6    16    21
7    23     8
8    28    25

In [695]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
0    20     7
2    16     8
3    18    23
5    28    20
6    16    21
7    23     8
8    28    25

# Birleştirme (Join) İşlemleri

In [696]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0     9    13     7
1    23    14    15
2    15    29    28
3    25     6     3
4    12     5    20

In [697]:
df2 = df1 + 99

In [698]:
df2

var1  var2  var3
0   108   112   106
1   122   113   114
2   114   128   127
3   124   105   102
4   111   104   119

In [699]:
pd.concat([df1,df2])

var1  var2  var3
0     9    13     7
1    23    14    15
2    15    29    28
3    25     6     3
4    12     5    20
0   108   112   106
1   122   113   114
2   114   128   127
3   124   105   102
4   111   104   119

In [700]:
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0     9    13     7
1    23    14    15
2    15    29    28
3    25     6     3
4    12     5    20
5   108   112   106
6   122   113   114
7   114   128   127
8   124   105   102
9   111   104   119

In [701]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [702]:
df2.columns = ["var1","var2","deg3"]

In [703]:
df2

var1  var2  deg3
0   108   112   106
1   122   113   114
2   114   128   127
3   124   105   102
4   111   104   119

In [704]:
df1

var1  var2  var3
0     9    13     7
1    23    14    15
2    15    29    28
3    25     6     3
4    12     5    20

In [705]:
pd.concat([df1, df2])

var1  var2  var3   deg3
0     9    13   7.0    NaN
1    23    14  15.0    NaN
2    15    29  28.0    NaN
3    25     6   3.0    NaN
4    12     5  20.0    NaN
0   108   112   NaN  106.0
1   122   113   NaN  114.0
2   114   128   NaN  127.0
3   124   105   NaN  102.0
4   111   104   NaN  119.0

In [706]:
pd.concat([df1, df2], join = "inner")

var1  var2
0     9    13
1    23    14
2    15    29
3    25     6
4    12     5
0   108   112
1   122   113
2   114   128
3   124   105
4   111   104

In [707]:
#pd.concat([df1, df2], join_axes = [df2.columns], ignore_index=True)

# İleri Birleştirme İşlemleri

In [708]:
import pandas as pd

In [709]:
#birebir birlestirme

In [710]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [711]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [712]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [713]:
pd.merge(df1, df2, on = "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [714]:
#coktan teke 

In [715]:
df3 = pd.merge(df1, df2)

In [716]:
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [717]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})

df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [718]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [719]:
# çoktan çoka

In [720]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [721]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [722]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

# Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [723]:
import seaborn as sns

In [724]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [725]:
df.shape

(1035, 6)

In [726]:
df.mean()

C:\Users\omars\AppData\Local\Temp\ipykernel_12888\3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [727]:
df["mass"].mean()

2.6381605847953216

In [728]:
df["mass"].count()

513

In [729]:
df["mass"].min()

0.0036

In [730]:
df["mass"].max()

25.0

In [731]:
df["mass"].sum()

1353.37638

In [732]:
df["mass"].std()

3.8186166509616046

In [733]:
df["mass"].var()

14.58183312700122

In [734]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [735]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# Gruplama İşlemleri

In [736]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [737]:
df.groupby("gruplar")

In [738]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [739]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [740]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [741]:
df.groupby("method")

In [742]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [743]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

# İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)

In [744]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [745]:
#aggregate

In [746]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [747]:
df.groupby("gruplar").aggregate([min, np.median, max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [748]:
df.groupby("gruplar").aggregate({"degisken1": "min", "degisken2": "max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

In [749]:
#filter

In [750]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [751]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [752]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [753]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [754]:
#transform

In [755]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [756]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [757]:
df_a = df.iloc[:,1:3]

In [758]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

In [759]:
#apply

In [760]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [761]:
df.apply(np.sum)

gruplar      ABCABC
degisken1       198
degisken2      2028
dtype: object

In [762]:
df["degisken1"].apply(np.mean)

0    10.0
1    23.0
2    33.0
3    22.0
4    11.0
5    99.0
Name: degisken1, dtype: float64

In [763]:
df.groupby("gruplar").apply(np.mean)

C:\Users\omars\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
C:\Users\omars\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

# Pivot Tablolar

In [764]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [765]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [766]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [767]:
#pivot ile table

In [768]:
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [769]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [770]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [771]:
titanic.pivot_table("survived", ["sex", age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

# Dış Kaynaklı Veri Okumak

In [772]:
import pandas as pd

In [773]:
#csv okuma
pd.read_csv("DATA/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [774]:
#txt okuma
pd.read_csv("DATA/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [775]:
#excel
pd.read_excel("DATA/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [776]:
df = pd.read_excel("DATA/ornekx.xlsx")

In [777]:
type(df)

pandas.core.frame.DataFrame

In [778]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [779]:
df.columns = ("A","B","C")

In [780]:
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [781]:
#sıfırdan txt okuma
tips = pd.read_csv("DATA/data.txt")

In [782]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4